name: CI Pipeline

on:
  pull_request:
    branches:
      - develop

jobs:
  build-test-and-analyze:
    name: Build, Test, and SonarQube Analysis
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ChargeUnity/backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for full SonarQube analysis

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      - name: Pre-fetch dependencies
        run: mvn dependency:go-offline

      - name: Build, Test, Generate Coverage and Analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn clean verify \
            -DskipITs=true \
            -T 4 \
            org.jacoco:jacoco-maven-plugin:report \
            org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.projectKey=Alxit0_tqs-test

      - name: Upload JaCoCo Coverage Report
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: ChargeUnity/backend/target/site/jacoco/

      - name: Run Cucumber Tests (Selenium)
        run: echo "placeholder for running Cucumber tests with Selenium"

      - name: (Optional) Run OWASP ZAP Scan
        run: echo "placeholder for running OWASP ZAP scan"
